settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: true
    interval: 100ms
server:
  status: true
  open: false
  port: 5001
  host: localhost
schema:
- name: /Users/Yousef/go/src/github.com/alowayed/ejaza-app
  path: /Users/Yousef/go/src/github.com/alowayed/ejaza-app
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    - gohtml
    - css
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - (/Users/Yousef/go/src/github.com/alowayed/ejaza-app/vendor)
    - /Users/Yousef/go/src/github.com/alowayed/ejaza-app/vendor
    - /Users/Yousef/go/src/github.com/alowayed/ejaza-app/vendor
